language: python
python:
  - "3.5"
addons:
  apt:
   packages:
     - xvfb
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ghostscript
install:
  #Remove the following line when pvacseq-client is first pushed to the live pypi site
  #This has been updated to pull from the live pypi site, instead of test pypi.
  #Not sure if it can or needs to be deleted altogether.
  - pip install pvacseq-client
  - pip install -e .[API]
  - mhcflurry-downloads fetch
  #with the newest version of the spec validator our swagger yml doesn't
  #validate anymore. Use a version that works.
  - pip install swagger-spec-validator==2.1.0
  #The MHCflurry output will differ depending on the version of tensorflow
  #The test data was created on tensorflow 1.8.0
  - pip install tensorflow==1.8.0
  - pip install connexion==1.4.2
  - pip install bokeh==0.13.0
  - pip install tornado==5.0.2
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
services:
  - postgresql
script:
  - TEST_FLAG=1 python3 -m unittest discover -v
  - prove --recurse --verbose
