name: py35
dependencies:
- openssl=1.0.2g=0
- pip=8.1.1=py35_0
- python=3.5.2
- readline=6.2=2
- sqlite
- tk
- wheel
- zlib
- requests
- pillow
- pip:
#- sphinxjp.themes.basicstrap
  - sphinx_rtd_theme
  - sphinxcontrib-programoutput
  - pvactools
